from datetime import datetime, timezone
from types import SimpleNamespace
from unittest.mock import ANY, AsyncMock, patch
from uuid import uuid4

import pytest

from app.core.exceptions import BadRequestException
from app.modules.students.models import AcademicStatus, StudentProfileStatus
from app.modules.students.schemas import StudentCreate, StudentUpdate
from app.modules.students.service import StudentService
from app.modules.users.models import UserRole


def _admin_actor():
    return SimpleNamespace(
        id=uuid4(),
        tenant_id=uuid4(),
        role=UserRole.ADMIN,
    )


@pytest.mark.asyncio
async def test_generate_admission_number_requires_tenant_prefix():
    tenant_id = uuid4()

    with patch(
        "app.modules.students.service.TenantRepository.get_by_id",
        new=AsyncMock(return_value=SimpleNamespace(id=tenant_id, admission_number_prefix=None)),
    ):
        with pytest.raises(BadRequestException) as exc_info:
            await StudentService.generate_admission_number(db=AsyncMock(), tenant_id=tenant_id)

    assert (
        exc_info.value.detail
        == "Admission number prefix has not been set for this school. Complete school setup before creating students."
    )


@pytest.mark.asyncio
async def test_generate_admission_number_uses_prefix_year_and_unique_suffix():
    tenant_id = uuid4()

    with patch(
        "app.modules.students.service.TenantRepository.get_by_id",
        new=AsyncMock(return_value=SimpleNamespace(id=tenant_id, admission_number_prefix="NHS")),
    ), patch(
        "app.modules.students.service.StudentRepository.get_by_admission_number",
        new=AsyncMock(return_value=None),
    ):
        admission_number = await StudentService.generate_admission_number(
            db=AsyncMock(),
            tenant_id=tenant_id,
        )

    current_year = datetime.now(timezone.utc).year
    assert admission_number.startswith(f"NHS-{current_year}-")
    assert len(admission_number.split("-")[-1]) == 5


@pytest.mark.asyncio
async def test_create_student_profile_rejects_manual_admission_number():
    actor = _admin_actor()
    student_user = SimpleNamespace(
        id=uuid4(),
        tenant_id=actor.tenant_id,
        role=UserRole.STUDENT,
    )
    payload = StudentCreate(
        user_id=student_user.id,
        admission_number="MANUAL-001",
    )

    with patch(
        "app.modules.students.service.UserRepository.get_user_by_id",
        new=AsyncMock(return_value=student_user),
    ), patch(
        "app.modules.students.service.StudentRepository.get_by_user_id",
        new=AsyncMock(return_value=None),
    ):
        with pytest.raises(BadRequestException) as exc_info:
            await StudentService.create_student_profile(
                db=AsyncMock(),
                actor=actor,
                payload=payload,
            )

    assert exc_info.value.detail == "Admission numbers are generated by the system and cannot be provided manually."


@pytest.mark.asyncio
async def test_update_student_profile_rejects_manual_admission_number_changes():
    actor = _admin_actor()
    student = SimpleNamespace(
        id=uuid4(),
        tenant_id=actor.tenant_id,
        user_id=uuid4(),
        admission_number="NHS-2026-12345",
    )

    with patch(
        "app.modules.students.service.StudentRepository.get_student_by_id",
        new=AsyncMock(return_value=student),
    ):
        with pytest.raises(BadRequestException) as exc_info:
            await StudentService.update_student_profile(
                db=AsyncMock(),
                actor=actor,
                student_id=student.id,
                payload=StudentUpdate(admission_number="OVERRIDE-001"),
            )

    assert exc_info.value.detail == "Admission numbers are generated by the system and cannot be changed manually."


@pytest.mark.asyncio
async def test_update_student_profile_auto_generates_admission_number_when_missing():
    actor = _admin_actor()
    student = SimpleNamespace(
        id=uuid4(),
        tenant_id=actor.tenant_id,
        user_id=uuid4(),
        admission_number=None,
        date_of_birth=None,
        gender=None,
        class_id=None,
        arm=None,
        admission_date=datetime.now(timezone.utc).date(),
        status=AcademicStatus.ACTIVE,
        profile_status=StudentProfileStatus.INCOMPLETE,
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )

    with patch(
        "app.modules.students.service.StudentRepository.get_student_by_id",
        new=AsyncMock(return_value=student),
    ), patch(
        "app.modules.students.service.StudentService.generate_admission_number",
        new=AsyncMock(return_value="NHS-2026-12345"),
    ) as generate_admission_number, patch(
        "app.modules.students.service.StudentRepository.update_student",
        new=AsyncMock(return_value=student),
    ):
        updated = await StudentService.update_student_profile(
            db=AsyncMock(),
            actor=actor,
            student_id=student.id,
            payload=StudentUpdate(
                date_of_birth=datetime(2012, 4, 3, tzinfo=timezone.utc).date(),
                gender="female",
                class_id=uuid4(),
            ),
        )

    assert updated.admission_number == "NHS-2026-12345"
    generate_admission_number.assert_awaited_once_with(
        db=ANY,
        tenant_id=actor.tenant_id,
    )


@pytest.mark.asyncio
async def test_update_student_profile_surfaces_missing_prefix_when_auto_generation_is_needed():
    actor = _admin_actor()
    student = SimpleNamespace(
        id=uuid4(),
        tenant_id=actor.tenant_id,
        user_id=uuid4(),
        admission_number=None,
        date_of_birth=None,
        gender=None,
        class_id=None,
        arm=None,
        admission_date=datetime.now(timezone.utc).date(),
        status=AcademicStatus.ACTIVE,
        profile_status=StudentProfileStatus.INCOMPLETE,
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )

    with patch(
        "app.modules.students.service.StudentRepository.get_student_by_id",
        new=AsyncMock(return_value=student),
    ), patch(
        "app.modules.students.service.StudentService.generate_admission_number",
        new=AsyncMock(
            side_effect=BadRequestException(
                detail=(
                    "Admission number prefix has not been set for this school. "
                    "Complete school setup before creating students."
                )
            )
        ),
    ):
        with pytest.raises(BadRequestException) as exc_info:
            await StudentService.update_student_profile(
                db=AsyncMock(),
                actor=actor,
                student_id=student.id,
                payload=StudentUpdate(
                    date_of_birth=datetime(2012, 4, 3, tzinfo=timezone.utc).date(),
                    gender="female",
                    class_id=uuid4(),
                ),
            )

    assert (
        exc_info.value.detail
        == "Admission number prefix has not been set for this school. Complete school setup before creating students."
    )
